### ISSUE TITLE
Any Updates to FuelSDK for C# planned?

### ISSUE THREAD

**Issue by scotthakel** [salesforce-marketingcloud/FuelSDK-CSharp#11]
Looking at the C# version of Fuel, it doesn’t look like its been updated in a long time, nor is there  evidence it is actively updated and enhanced with new functionality on a regular basis.  Can you describe what the update process is for the FuelSDK for C#, how often it is planned to be updated, etc.?  Some of the other languaged versions have more functionality, so just wondering what the plan is to update the C# version.

**Comment by jimmyjamez** [comment]
I second the comment/question made months ago on Feb 2. Why isn't this being supported? My company was encouraged to use FuelSDK as it was the latest and greatest and "new functionality will be added on a regular basis that will phase out the heavier soap methods."

**Comment by Laumania** [comment]
I second this too. Seems like nobody is looking at this repo. Years old pull requests...at least close/discard them, if you don't want them in - don't let them just hang there.

**Comment by fvedder** [comment]
I second this in addition to the previous two seconds.  Exact Target, if you don't have any desire to support .net, then say so.  I saw your examples and have a tight time frame for an implementation and question your level of support.  Did Mr. Clark did not respond?

**Comment by sahuja11** [comment]
Hello everyone,

Michael Clark does not work on the SDKs any longer. 

I realize the C# SDK has not been updated in a long time and the pull requests have gone unnoticed in the past, but we're trying to fix that now. My team will be working on these submitted requests soon.

The SDKs are supported and we encourage everyone to contribute to our efforts by submitting pull requests for any enhancements/bug fixes. From our side, we'll try to get through them in a timely manner.

Thanks!

**Comment by Jetski5822** [comment]
Hey @sahuja11 is there any updates on this?

It seems that both the Fuel SDK and the web service / web services are varied and lacking at the same time. Do you have a road map?

**Comment by Jetski5822** [comment]
Hey @sahuja11 - can I release an unofficial version of this? 

As you arent doing any maintenance to it, it might make sense?....

**Comment by smunuswami** [comment]
This is now resolved in the latest release.
