### ISSUE TITLE
ET_Client missing Proxy Credentials

### ISSUE THREAD

**Issue by Laumania** [salesforce-marketingcloud/FuelSDK-CSharp#13]
I have a case where I'm behind a Proxy and thereby need to be able to provide network credentials on the calls from the ET_Client.

**Comment by Laumania** [comment]
Turns out it is actually possible to set proxy credentials without changing the SDK.

``` CSharp
WebRequest.DefaultWebProxy.Credentials =  new NetworkCredential("USERNAME", "PASSWORD", "DOMAIN");
```

**Comment by MichaelAllenClark** [comment]
If you submit a pull request with an update to the Readme with those details, I'll pull it in.
