### ISSUE TITLE
Project doesn't compile when cloned

### ISSUE THREAD

**Issue by samay-kapadia-zocdoc** [salesforce-marketingcloud/FuelSDK-CSharp#30]
It looks like JWT.cs is missing from the FuelSDK-CSharp project. It looks like it is needed by ET_Client.cs

These look like they are left over from a merge conflict:
- https://github.com/salesforce-marketingcloud/FuelSDK-CSharp/blob/Dot9/objsamples/Sample_DataExtension.cs#L205
- https://github.com/salesforce-marketingcloud/FuelSDK-CSharp/blob/Dot9/objsamples/Tester.cs#L94

**Comment by smunuswami** [comment]
This is resolved in v1.0.0
