### ISSUE TITLE
JWT.cs missing from Dot9 branch

### ISSUE THREAD

**Issue by fbellgr** [salesforce-marketingcloud/FuelSDK-CSharp#33]
JWT.cs is referenced in the project file but is absent from the archive when downloading the zip.

**Comment by Jetski5822** [comment]
It's a nuget package isn't it?

**Comment by fbellgr** [comment]
Well, ET_Client is expecting it in it's own namespace. Off course, if you exclude the file, reinstall the JWT nuget and manually resolve the using directives, then it will build, provided you also unloaded the un-buildable objsamples project, in which the file Tester.cs ends with the following:

>>>>>>> f37a8eb93fcee5f49b5fa0ab1d09dd20d467aabb

Would you be so kind as to try to build it straight from a freshly unzipped, downloaded archive, please ?
I do not want to seem impolite but this repository is hardly reliable.

Thanks

**Comment by Jetski5822** [comment]
I'll check it out later for you.

Btw I don't worry for Salesforce, and yes the repo is a mess, but I will try and help.

**Comment by fbellgr** [comment]
My bad. Thanks. I'm actually trying to help them since I can fix it for myself. But it would be nice to be able to trust the source.

**Comment by Jetski5822** [comment]
They don't really maintain this product anymore, so wouldn't bank on support from Salesforce.

**Comment by smunuswami** [comment]
This is now resolved in latest release.
