### ISSUE TITLE
ETClient Login (401 or null ref)

### ISSUE THREAD

**Issue by ikramer-ssb** [salesforce-marketingcloud/FuelSDK-CSharp#44]
I've installed the SDK using `Install-Package SFMC.FuelSDK` from package manager. I'm trying to establish ETClient using the `clientId` and `clientSecret` params (without `jwt`), as referenced in the ReadMe.md.

I am able to get a token using Postman, but consistently get a `401 Unauthorized` from the SDK. Looking at the code, I have also tried to pass in the additional params of `authEndPoint` and `soapEndpoint`. This appears to get past the 401 error, but results in an argumentNullException thrown by Newtonsoft. Stack trace: ```   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at FuelSDK.ETClient.RefreshToken(Boolean force)
   at FuelSDK.ETClient..ctor(NameValueCollection parameters, RefreshState refreshState)```

It looks like this SDK will be very helpful, and I'm hoping you can help me find a solution. Thanks.

Possibly caused by lines 233-238 of ETClient.cs, where it is trying to parse all properties of the JWT implementation:

```            // Parse the response
            var parsedResponse = JObject.Parse(responseFromServer);
            InternalAuthToken = parsedResponse["legacyToken"].Value<string>().Trim();
            AuthToken = parsedResponse["accessToken"].Value<string>().Trim();
            AuthTokenExpiration = DateTime.Now.AddSeconds(int.Parse(parsedResponse["expiresIn"].Value<string>().Trim()));
            RefreshKey = parsedResponse["refreshToken"].Value<string>().Trim();

**Comment by sharif26** [comment]
rename App.config.transform to App.config and put your clientId and clientSecret there, then let us know.
Thanks.

**Comment by ikramer-ssb** [comment]
Thanks for the reply. Unfortunately no luck. My App.config references `<section name="fuelSDK" type="FuelSDK.FuelSDKConfigurationSection, FuelSDK" />` and `<fuelSDK appSignature="none" clientId="MYID" clientSecret="MYSECRET" />`

**Comment by ucladev** [comment]
@ikramer-ssb I was getting this error and I solved this by adding legacy=1 to the authEndPoint:

`
var parameters = new NameValueCollection();
parameters.Add("clientId", "...");
parameters.Add("clientSecret", "...");
parameters.Add("authEndPoint", "https://auth.exacttargetapis.com/v1/requestToken?legacy=1");

var et = new ETClient(parameters);
`

**Comment by smunuswami** [comment]
@ikramer-ssb , did @ucladev solution solved your issue?

**Comment by CharlesSchneider** [comment]
I was running in the same problem, and @ucladev's approach worked fine for me. 

parameters.Add("authEndPoint", "https://auth.exacttargetapis.com/v1/requestToken?legacy=1");

Thanks!

**Comment by ikramer-ssb** [comment]
@ucladev - Your solution works. Thank you for sharing!

**Comment by harrijon** [comment]
I was running at the same problem, and @ucladev's approach worked fine for me.

parameters.Add("authEndPoint", "https://auth.exacttargetapis.com/v1/requestToken?legacy=1");

Thanks!

**Comment by jeff881208** [comment]
Thanks

**Comment by jeff881208** [comment]
And will  this library will be update to math the latest soap API ？

**Comment by PratyushaY** [comment]
I have the same issue , adding authEndpoint doesnt help.
