### ISSUE TITLE
add authorisation token to SoapClient();

### ISSUE THREAD

**Issue by behradizadi** [salesforce-marketingcloud/FuelSDK-CSharp#45]
var client = new SoapClient();

any Idea how to add authentication token to the client in order to

 var client = new SoapClient();
RetrieveRequest rr = new RetrieveRequest();
client.Retrieve(rr, out requestID, out Results);
thanks

**Comment by smunuswami** [comment]
Please use the instruction provided in the read me file. Basically you have to add the SDK to your project using nuget. Follow the sample code provided in the readme. There are many sample code in unit test cases and sample project in https://github.com/salesforce-marketingcloud/FuelSDK-CSharp/tree/master/objsamples
