### ISSUE TITLE
ETClient (401) Unauthorized 

### ISSUE THREAD

**Issue by shinriel** [salesforce-marketingcloud/FuelSDK-CSharp#56]
I am using Visual Studio 2017, and install SFMC.FuelSDK by using Nuget.

I use this:

            NameValueCollection parameters = new NameValueCollection();
            parameters.Add("clientId", "xxxxxxxxxxxxx");
            parameters.Add("clientSecret", "xxxxxxxxxxxxxxxxx");
            ETClient myclient = new ETClient(parameters);

and get (401) Unauthorized. I tested my clientId and clientSecret with URL (https://auth.exacttargetapis.com/v1/requestToken), and they are valid.

Does anyone know what I did wrong?

**Comment by smunuswami** [comment]
can you please add the following line and try

parameters.Add("authEndPoint", "https://auth.exacttargetapis.com/v1/requestToken?legacy=1");

**Comment by shinriel** [comment]
It works. Thank you so much. Is there a document showing about this parameter, though?

**Comment by smunuswami** [comment]
This will be fixed in our next release.

**Comment by WalterBuesoTBG** [comment]
I still get a 401 error code after adding the authEndPoint parameter. Any ideas? 

Also @shinriel  what do you mean by testing your clientId and clientSecret at this url: (https://auth.exacttargetapis.com/v1/requestToken), I have that info, but how are you testing whether your clientId and clientSecret is valid? Can you give me an example?

**Comment by jonathan-icrossing** [comment]
Having the exact same issue, can someone please provide a solution? is breaking production.
