### ISSUE TITLE
Connecting to server machine failed!!

### ISSUE THREAD

**Issue by chandu2206** [salesforce-marketingcloud/FuelSDK-CSharp#66]
clientId and clientSecret has been updated in the App.config 
Is there any other option apart from disabling firewall ?

<img width="960" alt="sf api c" src="https://user-images.githubusercontent.com/39534202/52558704-3cc34100-2e19-11e9-918f-3f8bdc8f3c50.png">

**Comment by manivinesh** [comment]
Hello @chandu2206, Thanks for reporting this issue. We are checking and will get back asap.

**Comment by chandu2206** [comment]
@manivinesh have you got a chance to go through the issue

**Comment by manivinesh** [comment]
@chandu2206, We have identified the issue and working on a fix. It will be deployed as Patch release next week.

**Comment by sfdrogojan** [comment]
Hi @chandu2206! We released version [1.1.1](https://www.nuget.org/packages/SFMC.FuelSDK/1.1.1) of the FuelSDK with a fix.
